---
argocd_install_url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml



argocd_application_name: applications
argocd_application_repourl: https://github.com/Dialgatrainer02-lab/apps.git
argocd_application_ref: HEAD
argocd_application_namespace: argocd
argocd_application_path: apps
argocd_manifest_path: /tmp
