---
argocd_application_name: applications
argocd_application_repourl: https://github.com/Dialgatrainer02-lab/apps.git
argocd_application_ref: HEAD
argocd_application_namespace: argocd
argocd_application_path: apps