---
# - name: Wait 300 seconds for port 22
# ansible.builtin.wait_for:

# port: "22"
# host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
# search_regex: OpenSSH
# delay: "10"
# timeout: "300"
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Include OS-specific installation tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml"

- name: Write config
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: "0755"
  notify:
    - Restart containerd

- name: Start containerd
  ansible.builtin.systemd_service:
    enabled: true
    name: containerd
    state: "started"

- name: Ensure sysctl params required by setup
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }


- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Start kubelet
  ansible.builtin.systemd_service:
    enabled: true
    name: kubelet
    state: "started"

# - name: Check cluster initalisation
  # ansible.builtin.stat:
    # path: /etc/kubernetes/admin.conf
  # register: k8_cluster_admin_conf

- name: Install helm diff
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Controlplane specific steps
  ansible.builtin.include_tasks:
    file: Controlplane.playbook.yml
  when: "'controlplane' in group_names"
  tags:
    - controlplane

- name: Worker specific steps
  ansible.builtin.include_tasks:
    file: Worker.playbook.yml
  when: "'worker' in group_names"
  tags:
    - workers

- name: Install load balancer
  ansible.builtin.include_tasks:
    file: "lb/{{ k8_cluster_lb }}.yml"


- name: Get Cluster information
  kubernetes.core.k8s_cluster_info:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  register: k8_cluster_api_status
  when: "'controlplane' in group_names"

